name = "ps99rap-worker"
main = "worker/index.js"
compatibility_date = "2024-01-01"

# Cron trigger — polls every 5 minutes
[triggers]
crons = ["*/5 * * * *"]

# KV namespace binding
# After running `wrangler kv:namespace create PS99_KV` paste the returned id below
[[kv_namespaces]]
binding  = "PS99_KV"
id       = "102231a235bc4af08c1929dd1223081e"
